COMMON = 1
UNCOMMON = 1 
MONTH = 4
MONTH_DAYS = 30

VITAMINE_PER_COMMON = COMMON * 5
VITAMINE_PER_COMMON_DAYS = 10
BLUE_CARDS = COMMON * 25
BLUE_CARDS_WEEKS = 10
total = VITAMINE_PER_COMMON * VITAMINE_PER_COMMON_DAYS * MONTH_DAYS + BLUE_CARDS * BLUE_CARDS_WEEKS * MONTH


print("초록물고기 %2d" % total)